# Generated by Django 4.2.4 on 2023-08-12 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='категория')),
                ('category_description', models.TextField(blank=True, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='товар')),
                ('product_description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='изображение')),
                ('product_price', models.FloatField(verbose_name='цена за покупку')),
                ('date_of_creation', models.DateField(verbose_name='дата создания')),
                ('date_of_last_change', models.DateField(verbose_name='дата последнего изменения')),
                ('product_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='категория')),
            ],
        ),
    ]
