# Generated by Django 4.2.4 on 2023-08-13 00:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_date_of_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_of_creation',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_of_last_change',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата последнего изменения'),
        ),
    ]
